import { uuid, text, timestamp, index } from 'drizzle-orm/pg-core'
import { platform } from './tenants'
import { users } from './users'

/**
 * Opaque session tokens. The token itself is the primary key — generated by
 * `@kantr/auth#generateSessionToken` (40 chars, ~238 bits entropy from a
 * CSPRNG). No JWT, no server-side signature; revocation is a DELETE.
 *
 * Rolling refresh: when a request comes in with <1/3 lifetime remaining,
 * `validateSessionToken` updates `expires_at` in place.
 */
export const sessions = platform.table(
  'sessions',
  {
    token: text('token').primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userIdx: index('sessions_user_id_idx').on(t.userId),
  }),
)

export type Session = typeof sessions.$inferSelect
export type NewSession = typeof sessions.$inferInsert
